apiVersion: v2
name: huginn
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
# this is not the real version, it looks via git shas?
appVersion: 1.16.0
home: https://github.com/huginn/huginn
icon: https://camo.githubusercontent.com/f7da893be2c2f5f765f2436296656e7d25962437/68747470733a2f2f7261772e6769746875622e636f6d2f687567696e6e2f687567696e6e2f6d61737465722f6d656469612f687567696e6e2d6c6f676f2e706e67
maintainers:
  - name: jjasghar
    email: jjasghar@gmail.com
  - name: paulczar
    email: username.taken@gmail.com
sources:
  - https://github.com/huginn/huginn
keywords:
  - ruby
  - huginn
  - automation
dependencies:
- name: postgresql
  version: "8.7.3"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
