{{-  $domain := printf "%s:%.0f" .Values.app.domain .Values.service.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "huginn.fullname" . }}-delayed-job
  labels:
    {{- include "huginn.labels" . | nindent 4 }}
    app.kubernetes.io/component: delayed-job
spec:
  replicas: {{ .Values.delayedJob.replicaCount }}
  selector:
    matchLabels:
      {{- include "huginn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: delayed-job
  template:
    metadata:
      labels:
        {{- include "huginn.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: delayed-job
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "huginn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: [ "/scripts/init" ]
          args: [ "script/delayed_job", "run" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          env:
            - name: APP_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "app_secret_token"
            - name: INVITATION_CODE
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "invitation_code"
            - name: DOMAIN
              value: {{ $domain | quote }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
            {{- if .Values.postgresql.enabled }}
              {{ with .Values.postgresql }}
            - name: HUGINN_DATABASE_NAME
              value: {{ .postgresqlDatabase | quote }}
            - name: HUGINN_DATABASE_USERNAME
              value: {{ .postgresqlUsername | quote }}
              {{ end }}
            - name: DATABASE_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_ADAPTER
              value: postgresql
            {{- else }}
              {{ with .Values.externalDatabase }}
            - name: HUGINN_DATABASE_NAME
              value: {{ .database | quote }}
            - name: HUGINN_DATABASE_USERNAME
              value: {{ .user | quote }}
            - name: DATABASE_HOST
              value: {{ .host | quote }}
            - name: DATABASE_PORT
              value: {{ .port | quote }}
              {{- end }}
              {{- if eq .Values.externalDatabase.type "postgresql" }}
            - name: DATABASE_ADAPTER
              value: postgresql
              {{- else }}
            - name: DATABASE_ADAPTER
              value: mysql2
              {{- end }}
            {{- end }}
            - name: HUGINN_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "database_password"
            - name: SMTP_DOMAIN
              value: {{ .Values.smtp.domain | quote }}
            - name: SMTP_USER_NAME
              value: {{ .Values.smtp.username | quote }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "smtp_password"
            - name: SMTP_SERVER
              value: {{ .Values.smtp.server | quote }}
            - name: SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: SMTP_AUTHENTICATION
              value: {{ .Values.smtp.authentication | quote }}
            - name: SMTP_ENABLE_STARTTLS_AUTO
              value: {{ .Values.smtp.enableStartttlAuto | quote }}
            - name: EMAIL_FROM_ADDRESS
              value: {{ .Values.emailFromAddress | quote }}
            {{- if .Values.oauth.twitter.enabled }}
            - name: TWITTER_OAUTH_KEY
              value: {{ .Values.oauth.twitter.key | quote }}
            - name: TWITTER_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "twitter_oauth_secret"
            {{- end }}
            {{- if .Values.oauth.thirty_seven_signals.enabled }}
            - name: THIRTY_SEVEN_SIGNALS_OAUTH_KEY
              value: {{ .Values.oauth.thirty_seven_signals.key | quote }}
            - name: THIRTY_SEVEN_SIGNALS_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "thirty_seven_signals_oauth_secret"
            {{- end }}
            {{- if .Values.oauth.github.enabled }}
            - name: GITHUB_OAUTH_KEY
              value: {{ .Values.oauth.github.key | quote }}
            - name: GITHUB_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "github_oauth_secret"
            {{- end }}
            {{- if .Values.oauth.tumblr.enabled }}
            - name: TUMBLR_OAUTH_KEY
              value: {{ .Values.oauth.tumblr.key | quote }}
            - name: TUMBLR_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "tumblr_oauth_secret"
            {{- end }}
            {{- if .Values.oauth.dropbox.enabled }}
            - name: DROPBOX_OAUTH_KEY
              value: {{ .Values.oauth.dropbox.key | quote }}
            - name: DROPBOX_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "dropbox_oauth_secret"
            {{- end }}
            {{- if .Values.oauth.wunderlist.enabled }}
            - name: WUNDERLIST_OAUTH_KEY
              value: {{ .Values.oauth.wunderlist.key | quote }}
            - name: WUNDERLIST_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "wunderlist_oauth_secret"
            {{- end }}
            {{- if .Values.oauth.evernote.enabled }}
            - name: EVERNOTE_OAUTH_KEY
              value: {{ .Values.oauth.evernote.key | quote }}
            - name: EVERNOTE_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "huginn.fullname" . }}
                  key: "evernote_oauth_secret"
            - name: USE_EVERNOTE_SANDBOX
              value: {{ .Values.oauth.evernote.use_sandbox }}
            {{- end }}
            {{- if .Values.requireConfirmedEmail }}
            - name: REQUIRE_CONFIRMED_EMAIL
              value: {{ .Values.requireConfirmedEmail | quote }}
            {{- end }}
            {{- if .Values.allowUnconfirmedAccessFor }}
            - name: ALLOW_UNCONFIRMED_ACCESS_FOR
              value: "{{ .Values.allowUnconfirmedAccessFor }}"
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
