apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huginn.fullname" . }}
  labels:
    {{- include "huginn.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.oauth.twitter.enabled .Values.oauth.twitter.secret }}
  twitter_oauth_secret: {{ .Values.oauth.twitter.secret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oauth.thirty_seven_signals.enabled .Values.oauth.thirty_seven_signals.secret }}
  thirty_seven_signals_oauth_secret: {{ .Values.oauth.thirty_seven_signals.secret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oauth.github.enabled .Values.oauth.github.secret }}
  github_oauth_secret: {{ .Values.oauth.github.secret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oauth.tumblr.enabled .Values.oauth.tumblr.secret }}
  tumblr_oauth_secret: {{ .Values.oauth.tumblr.secret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oauth.dropbox.enabled .Values.oauth.dropbox.secret }}
  dropbox_oauth_secret: {{ .Values.oauth.dropbox.secret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oauth.wunderlist.enabled .Values.oauth.wunderlist.secret }}
  wunderlist_oauth_secret: {{ .Values.oauth.wunderlist.secret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oauth.evernote.enabled .Values.oauth.evernote.secret }}
  evernote_oauth_secret: {{ .Values.oauth.evernote.secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret_token }}
  app_secret_token: {{ .Values.secret_token | b64enc | quote }}
  {{- else }}
  app_secret_token: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.smtp.password }}
  smtp_password: {{ .Values.smtp.password | b64enc | quote }}
  {{- else }}
  smtp_password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  database_password: {{ .Values.postgresql.postgresqlPassword }}
  {{- else }}
  database_password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.invitationCode }}
  invitation_code: {{ .Values.invitationCode | b64enc | quote }}
  {{- else }}
  invitation_code: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.aws.enabled .Values.aws.access_key }}
  aws_access_key: {{ .Values.aws.access_key | b64enc | quote }}
  {{- end }}